### ISSUE TITLE
Traducir BezierDetail de pagina p5js

### ISSUE THREAD

**Issue by holomorfo** [sptm-unam/sptm-docs#3]
Traducir contenido de archivo es.json en pagina de p5js
Lineas 540 a 548
    "bezierDetail": {
      "description": [
        "Sets the resolution at which Bezier's curve is displayed. The default value is 20.",
        "Note, This function is only useful when using the WEBGL renderer as the default canvas renderer does not use this information."
      ],
      "params": {
        "detail": "Number: resolution of the curves"
      }
    },

**Comment by ninioArtillero** [comment]
ya quedó :P 

https://github.com/processing/p5.js-website/pull/1326

**Comment by holomorfo** [comment]
Muy Xavier, ya quedo
